[general]
static = yes
writeprotect = yes
autofallthrough = yes
clearglobalvars = yes

[bksp-in]
exten => ${SMOL_PBX_USERNAME},1,Dial(PJSIP/${SMOL_LOCAL_USERNAME})

[bksp-out]
exten => _[0-9].,1,Dial(PJSIP/${EXTEN}@bksp)
  same => n,Hangup()

exten => _[0-9],1,Dial(PJSIP/${EXTEN}@bksp)
  same => n,Hangup()

exten => _*.,1,Set(CALLERID(all)=${SMOL_CID})
  same => n,Dial(PJSIP/${EXTEN}@bksp)
  same => n,Hangup()

; Catch-all for unhandled SIP events (e.g. BLF/MWI subscribe)
[anonymous-sink-ctx]
exten => _X.,1,Hangup()