[global]
debug = yes
direct_media = no

[default-transport](!)
type = transport
symmetric_transport = yes

[transport-remote-bksp](default-transport)
protocol = tls
bind = 0.0.0.0:0
verify_server = yes
ca_list_path = /etc/ssl/certs
method = tlsv1_2
tcp_keepalive_enable = yes

; Transport on a local network
[transport-local-tcp](default-transport)
protocol = tcp
bind = 0.0.0.0:5060

; TLS (5061) allowing access from external network with mandatory SRTP
[client](!)
transport = transport-local-tcp
type = endpoint
context = bksp-out
direct_media = no

dtmf_mode = rfc4733
disallow = all
allow = opus, ulaw, alaw, g722

[auth-userpass](!)
type = auth
auth_type = userpass

[aor-single-reg](!)
type = aor
max_contacts = 1
qualify_frequency = 30
remove_existing = yes
remove_unavailable = yes

; Default phone
[auth100](auth-userpass)
username = ${SMOL_LOCAL_USERNAME}
password = ${SMOL_LOCAL_PASSWORD}

[100](aor-single-reg)

[100](client)
auth = auth100
aors = 100
callerid = ${SMOL_CID}

; BKSP upstream
[auth-bksp]
type = auth
auth_type = userpass
username = ${SMOL_PBX_USERNAME}
password = ${SMOL_PBX_PASSWORD}

[aor-bksp]
type = aor
contact = sip:sip.bksp.in
qualify_frequency = 60

[reg-bksp]
type = registration
transport = transport-remote-bksp
outbound_auth = auth-bksp
server_uri = sip:sip.bksp.in:5061
client_uri = sip:${SMOL_PBX_USERNAME}@sip.bksp.in
retry_interval = 60
expiration = 120
contact_user = ${SMOL_PBX_USERNAME}

[bksp]
type = endpoint
transport = transport-remote-bksp
context = bksp-in
disallow = all
allow = opus, alaw, ulaw, g722
dtmf_mode = rfc4733
outbound_auth = auth-bksp
aors = aor-bksp
from_user = ${SMOL_PBX_USERNAME}
from_domain = sip.bksp.in
direct_media = no
media_encryption = sdes
media_encryption_optimistic = no
rtp_symmetric = yes
force_rport = yes
rewrite_contact = yes
bind_rtp_to_media_address = yes

[identify-bksp]
type = identify
endpoint = bksp
match = sip.bksp.in