services:
  wireguard:
    build: wireguard
    restart: always
    network_mode: host
    env_file: .env
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ["CMD", "wg", "show", "bksp-siprnet"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 5s
    logging:
      driver: "local"
      options:
        max-size: "1m"
        max-file: "4"

  asterisk:
    build: asterisk
    restart: always
    network_mode: host
    env_file: .env
    depends_on:
      wireguard:
        condition: service_healthy
    extra_hosts:
      sip.bksp.in: "fd91:652e:271a:e164:100c::1"
    volumes:
      # Share system timezone
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "local"
      options:
        max-size: "1m"
        max-file: "4"
    deploy:
      resources:
        limits:
          memory: 512M

  caddy:
    image: caddy:latest
    restart: always
    network_mode: host
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./tftpboot:/tftpboot:ro
    logging:
      driver: "local"
      options:
        max-size: "1m"
        max-file: "4"
    deploy:
      resources:
        limits:
          memory: 128M