[Interface]
ListenPort = 37201
Address = fd91:652e:271a:e164::1/64
PrivateKey = REDACTED
MTU = 1420

# Allow ICMPv6 "Packet Too Big", ICMPv6 "Echo Request", TCP 5061 (SIP TLS), and UDP 31600-31900 (RTP)
PostUp  = ip6tables -A INPUT -i %i -p ipv6-icmp --icmpv6-type packet-too-big -j ACCEPT
PostUp  = ip6tables -A INPUT -i %i -p ipv6-icmp --icmpv6-type echo-request -j ACCEPT
PostUp  = ip6tables -A INPUT -i %i -p tcp --dport 5061 -j ACCEPT
PostUp  = ip6tables -A INPUT -i %i -p udp --dport 31600:31900 -j ACCEPT
PostUp  = ip6tables -A INPUT -i %i -j DROP
PostDown = ip6tables -D INPUT -i %i -p ipv6-icmp --icmpv6-type packet-too-big -j ACCEPT
PostDown = ip6tables -D INPUT -i %i -p ipv6-icmp --icmpv6-type echo-request -j ACCEPT
PostDown = ip6tables -D INPUT -i %i -p tcp --dport 5061 -j ACCEPT
PostDown = ip6tables -D INPUT -i %i -p udp --dport 31600:31900 -j ACCEPT
PostDown = ip6tables -D INPUT -i %i -j DROP

# Example peer "1234"
[Peer]
AllowedIPs = fd91:652e:271a:e164::1234/128
PublicKey = REDACTED
PresharedKey = REDACTED
PersistentKeepalive = 30